/**
 * The lab book's sections for a level. Task is the printed brief. Theory meets the parts first
 * (one spread per part: what each leg and marking means), then the level's class step by step
 * with its live labs, then the check. Math is the formulas, a worked example and a practice
 * question, generated by the exam drills (so the numbers are always the solver's).
 */
import { GENERATORS } from '../drills/generators';
import { classForLevel } from '../learn/classes';
import type { LearnClass, Step } from '../learn/types';
import type { LevelDef } from '../levels/types';

export type Section = 'task' | 'theory' | 'math';
export const SECTIONS: Section[] = ['task', 'theory', 'math'];

export type PartId = 'led' | 'resistor' | 'breadboard' | 'multimeter' | 'capacitor' | 'button' | 'battery';

export interface PartExplainer {
  id: PartId;
  name: string;
  /** One line: what it does. */
  job: string;
  /** Callouts on the model: what each bit is. */
  facts: { label: string; text: string }[];
}

export interface Formula {
  name: string;
  /** Shown big, e.g. "V = I × R". */
  expr: string;
  /** What each symbol means. */
  terms: [string, string][];
  /** When to use it, in one line. */
  when: string;
}

export type Spread =
  | { kind: 'part'; part: PartExplainer }
  | { kind: 'step'; cls: LearnClass; step: Step; index: number }
  | { kind: 'check'; cls: LearnClass }
  | { kind: 'formulas'; formulas: Formula[] }
  | { kind: 'worked'; generator: string; seed: number }
  | { kind: 'practice'; generator: string };

export const PARTS: Record<PartId, PartExplainer> = {
  led: {
    id: 'led', name: 'LED', job: 'Lights up when current flows through it the right way: from the long leg to the short one.',
    facts: [
      { label: 'Long leg', text: 'the anode (+): it goes toward the supply' },
      { label: 'Short leg', text: 'the cathode (−): it goes toward ground' },
      { label: 'Flat side', text: 'on the rim, next to the cathode' },
      { label: 'About 2 V', text: 'a red LED drops about 2 V when lit, and needs a resistor to limit its current' },
    ],
  },
  resistor: {
    id: 'resistor', name: 'Resistor', job: 'Resists current: it sets how much flows, and turns the voltage it takes into heat.',
    facts: [
      { label: '1st band', text: 'first digit' },
      { label: '2nd band', text: 'second digit' },
      { label: '3rd band', text: 'how many zeros (the multiplier)' },
      { label: 'Gold band', text: '± 5 % tolerance. Either way round works: resistors have no polarity' },
    ],
  },
  breadboard: {
    id: 'breadboard', name: 'Breadboard', job: 'Holds parts and joins them without solder: metal clips under the holes connect them in strips.',
    facts: [
      { label: 'Columns of 5', text: 'the five holes a–e in a column are one strip, and f–j another' },
      { label: 'Centre gap', text: 'the two halves are not connected across it' },
      { label: 'Rails', text: 'the long rows along the edges: + (red) and − (blue) for the supply' },
      { label: 'Same strip', text: 'both legs of a part in one strip means the part is shorted out' },
    ],
  },
  multimeter: {
    id: 'multimeter', name: 'Multimeter', job: 'Measures what the circuit is doing: voltage, current or resistance, picked on the dial.',
    facts: [
      { label: 'Black lead', text: 'COM: usually on ground (the − rail)' },
      { label: 'Red lead', text: 'the point you want to know about' },
      { label: 'V', text: 'voltage between the leads: measure across a part' },
      { label: 'A and Ω', text: 'A goes in series (the meter becomes a wire); Ω only with the power off' },
    ],
  },
  capacitor: {
    id: 'capacitor', name: 'Electrolytic capacitor', job: 'Stores charge: it fills up through a resistor and its voltage rises on a curve.',
    facts: [
      { label: 'Stripe', text: 'marks the − leg' },
      { label: 'Long leg', text: '+ : it must sit on the higher voltage' },
      { label: '100 µF', text: 'its capacitance: more µF takes longer to fill' },
      { label: 'Backwards', text: 'a reversed electrolytic can fail, so check the stripe' },
    ],
  },
  button: {
    id: 'button', name: 'Push button', job: 'A switch you hold: it joins its legs only while it is pressed.',
    facts: [
      { label: 'Pressed', text: 'closed: current can flow' },
      { label: 'Let go', text: 'open: the circuit is broken' },
    ],
  },
  battery: {
    id: 'battery', name: 'AA cell', job: 'A small chemical pump: it lifts every charge that passes through it by 1.5 V.',
    facts: [
      { label: '+ end', text: 'the one with the bump: the higher voltage' },
      { label: '− end', text: 'the flat end' },
      { label: '1.5 V', text: 'each; in series, + to −, they add up' },
    ],
  },
};

export const FORMULAS: Record<string, Formula> = {
  ohm: {
    name: "Ohm's law", expr: 'V = I × R',
    terms: [['V', 'voltage across the part (volts)'], ['I', 'current through it (amps)'], ['R', 'its resistance (ohms)']],
    when: 'Any resistor: know two, work out the third (I = V ÷ R, R = V ÷ I).',
  },
  led: {
    name: 'LED resistor', expr: 'R = (V_supply − V_LED) ÷ I',
    terms: [['V_supply', 'the supply voltage'], ['V_LED', 'the LED’s drop, about 2 V for red'], ['I', 'the current you want, e.g. 15 mA']],
    when: 'The resistor takes whatever voltage the LED doesn’t.',
  },
  kvl: {
    name: 'Voltages round a loop', expr: 'V_supply = V₁ + V₂ + …',
    terms: [['V₁, V₂', 'the voltage each part takes']],
    when: 'Going once round any loop, the drops add up to what the supply gives (Kirchhoff’s voltage law).',
  },
  series: {
    name: 'Series and parallel', expr: 'series: I same, V adds · parallel: V same, I adds',
    terms: [['series', 'one path: the same current through every part'], ['parallel', 'side by side: each branch gets the full voltage, currents add']],
    when: 'Two LEDs in series share one current; in parallel the supply feeds both.',
  },
  divider: {
    name: 'Voltage divider', expr: 'V_out = V_in × R₂ ÷ (R₁ + R₂)',
    terms: [['R₁', 'top resistor (to the supply)'], ['R₂', 'bottom resistor (to ground)'], ['I', 'V_in ÷ (R₁ + R₂) flows through both']],
    when: 'The ratio sets the voltage; the size sets the current.',
  },
  kcl: {
    name: 'Currents at a junction', expr: 'I_in = I_1 + I_2 + …',
    terms: [['I_in', 'the current arriving at a point'], ['I_1, I_2', 'the currents leaving it by each branch']],
    when: 'Whatever flows into a point flows out again (Kirchhoff’s current law): parallel branch currents add up at the supply.',
  },
  bridge: {
    name: 'Balanced bridge', expr: 'R2 ÷ R1 = R4 ÷ R3',
    terms: [['R1, R2', 'the left divider (top, bottom)'], ['R3, R4', 'the right divider (top, bottom)']],
    when: 'When the ratios match, both taps sit at the same voltage and the meter between them reads zero.',
  },
  rc: {
    name: 'RC time constant', expr: 'τ = R × C',
    terms: [['τ', 'the time to reach 63 % of the final voltage (seconds)'], ['R', 'ohms'], ['C', 'farads (100 µF = 0.0001 F)'], ['V(t)', 'V × (1 − e^(−t/τ))']],
    when: 'After 1 τ the capacitor is 63 % full, after 5 τ it’s all but full.',
  },
};

const LEVEL: Record<string, { parts: PartId[]; formulas: string[]; generators: string[] }> = {
  'w0-01-first-light': { parts: ['led', 'resistor', 'breadboard'], formulas: ['ohm', 'led'], generators: ['led-resistor', 'ohm'] },
  'w0-02-wrong-way-round': { parts: ['led', 'multimeter'], formulas: ['kvl', 'led'], generators: ['led-resistor', 'series-voltage'] },
  'w0-03-side-by-side': { parts: ['led', 'resistor'], formulas: ['series', 'led'], generators: ['series-voltage', 'parallel-total'] },
  'w0-04-split-the-difference': { parts: ['resistor', 'multimeter'], formulas: ['divider', 'ohm'], generators: ['divider'] },
  'w0-05-slow-blink': { parts: ['capacitor', 'button'], formulas: ['rc'], generators: ['rc-charge'] },
  'w0-06-fork-in-the-road': { parts: ['resistor', 'led'], formulas: ['kcl', 'ohm'], generators: ['parallel-total', 'series-parallel'] },
  'w0-07-push-to-light': { parts: ['button', 'breadboard'], formulas: ['ohm', 'led'], generators: ['led-resistor'] },
  'w0-08-stack-them-up': { parts: ['battery', 'multimeter'], formulas: ['kvl', 'led'], generators: ['series-voltage'] },
  'w0-09-balance-the-bridge': { parts: ['resistor', 'multimeter'], formulas: ['bridge', 'divider'], generators: ['bridge', 'divider'] },
};

/** A stable seed per level so the worked example is the same each time you open it. */
const seedOf = (id: string) => [...id].reduce((h, c) => (h * 31 + c.charCodeAt(0)) >>> 0, 7);

export function spreads(level: LevelDef, section: Section): Spread[] {
  const plan = LEVEL[level.id] ?? { parts: [], formulas: ['ohm'], generators: ['ohm'] };
  if (section === 'theory') {
    const cls = classForLevel(level.id);
    return [
      ...plan.parts.map((p) => ({ kind: 'part' as const, part: PARTS[p] })),
      ...(cls ? cls.steps.map((step, index) => ({ kind: 'step' as const, cls, step, index })) : []),
      ...(cls ? [{ kind: 'check' as const, cls }] : []),
    ];
  }
  if (section === 'math') {
    const gens = plan.generators.filter((g) => GENERATORS.some((x) => x.id === g));
    return [
      { kind: 'formulas', formulas: plan.formulas.map((f) => FORMULAS[f]!).filter(Boolean) },
      ...gens.map((g) => ({ kind: 'worked' as const, generator: g, seed: seedOf(level.id + g) })),
      { kind: 'practice', generator: gens[0] ?? 'ohm' },
    ];
  }
  return [];
}
