/**
 * The lab book's sections for a level. Task is the printed brief. Theory meets the parts first
 * (one spread per part: what each leg and marking means), then the level's class step by step
 * with its live labs, then the check. Math is the formulas, a worked example and a practice
 * question, generated by the exam drills (so the numbers are always the solver's).
 */
import { GENERATORS } from '../drills/generators';
import { classForLevel } from '../learn/classes';
import type { LearnClass, Step } from '../learn/types';
import type { LevelDef } from '../levels/types';

export type Section = 'task' | 'theory' | 'math';
export const SECTIONS: Section[] = ['task', 'theory', 'math'];

export type PartId = 'led' | 'resistor' | 'breadboard' | 'multimeter' | 'capacitor' | 'button' | 'battery' | 'transistor'
  | 'diode' | 'pot' | 'mosfet' | 'regulator' | 'chip' | 'toggle';

export interface PartExplainer {
  id: PartId;
  name: string;
  /** One line: what it does. */
  job: string;
  /** Callouts on the model: what each bit is. */
  facts: { label: string; text: string }[];
}

export interface Formula {
  name: string;
  /** Shown big, e.g. "V = I × R". */
  expr: string;
  /** What each symbol means. */
  terms: [string, string][];
  /** When to use it, in one line. */
  when: string;
}

export type Spread =
  | { kind: 'part'; part: PartExplainer }
  | { kind: 'step'; cls: LearnClass; step: Step; index: number }
  | { kind: 'check'; cls: LearnClass }
  | { kind: 'formulas'; formulas: Formula[] }
  | { kind: 'worked'; generator: string; seed: number }
  | { kind: 'practice'; generator: string };

export const PARTS: Record<PartId, PartExplainer> = {
  led: {
    id: 'led', name: 'LED', job: 'Lights up when current flows through it the right way: from the long leg to the short one.',
    facts: [
      { label: 'Long leg', text: 'the anode (+): it goes toward the supply' },
      { label: 'Short leg', text: 'the cathode (−): it goes toward ground' },
      { label: 'Flat side', text: 'on the rim, next to the cathode' },
      { label: 'About 2 V', text: 'a red LED drops about 2 V when lit, and needs a resistor to limit its current' },
    ],
  },
  resistor: {
    id: 'resistor', name: 'Resistor', job: 'Resists current: it sets how much flows, and turns the voltage it takes into heat.',
    facts: [
      { label: '1st band', text: 'first digit' },
      { label: '2nd band', text: 'second digit' },
      { label: '3rd band', text: 'how many zeros (the multiplier)' },
      { label: 'Gold band', text: '± 5 % tolerance. Either way round works: resistors have no polarity' },
    ],
  },
  breadboard: {
    id: 'breadboard', name: 'Breadboard', job: 'Holds parts and joins them without solder: metal clips under the holes connect them in strips.',
    facts: [
      { label: 'Columns of 5', text: 'the five holes a–e in a column are one strip, and f–j another' },
      { label: 'Centre gap', text: 'the two halves are not connected across it' },
      { label: 'Rails', text: 'the long rows along the edges: + (red) and − (blue) for the supply' },
      { label: 'Same strip', text: 'both legs of a part in one strip means the part is shorted out' },
    ],
  },
  multimeter: {
    id: 'multimeter', name: 'Multimeter', job: 'Measures what the circuit is doing: voltage, current or resistance, picked on the dial.',
    facts: [
      { label: 'Black lead', text: 'COM: usually on ground (the − rail)' },
      { label: 'Red lead', text: 'the point you want to know about' },
      { label: 'V', text: 'voltage between the leads: measure across a part' },
      { label: 'A and Ω', text: 'A goes in series (the meter becomes a wire); Ω only with the power off' },
    ],
  },
  capacitor: {
    id: 'capacitor', name: 'Electrolytic capacitor', job: 'Stores charge: it fills up through a resistor and its voltage rises on a curve.',
    facts: [
      { label: 'Stripe', text: 'marks the − leg' },
      { label: 'Long leg', text: '+ : it must sit on the higher voltage' },
      { label: '100 µF', text: 'its capacitance: more µF takes longer to fill' },
      { label: 'Backwards', text: 'a reversed electrolytic can fail, so check the stripe' },
    ],
  },
  button: {
    id: 'button', name: 'Push button', job: 'A switch you hold: it joins its legs only while it is pressed.',
    facts: [
      { label: 'Pressed', text: 'closed: current can flow' },
      { label: 'Let go', text: 'open: the circuit is broken' },
    ],
  },
  battery: {
    id: 'battery', name: 'AA cell', job: 'A small chemical pump: it lifts every charge that passes through it by 1.5 V.',
    facts: [
      { label: '+ end', text: 'the one with the bump: the higher voltage' },
      { label: '− end', text: 'the flat end' },
      { label: '1.5 V', text: 'each; in series, + to −, they add up' },
    ],
  },
  transistor: {
    id: 'transistor', name: 'NPN transistor', job: 'A current-controlled switch: a small current into the base lets a bigger one flow from collector to emitter.',
    facts: [
      { label: 'Flat face', text: 'with it towards you, a BC547’s legs are C, B, E (here it faces away: E, B, C)' },
      { label: 'Base', text: 'the control leg: it turns on at about 0.7 V above the emitter' },
      { label: 'Gain β', text: 'collector current up to about 200 × base current' },
      { label: 'Base resistor', text: 'always: it sets the base current, or the base takes far too much' },
    ],
  },
  diode: {
    id: 'diode', name: 'Diode', job: 'A one-way valve: current flows from the anode to the banded cathode, and is blocked the other way.',
    facts: [
      { label: 'Band', text: 'the cathode (−): current comes out here' },
      { label: 'Plain end', text: 'the anode (+)' },
      { label: '0.7 V', text: 'what a silicon diode keeps when it conducts' },
      { label: 'Reverse', text: 'blocks up to its rating: 75 V (1N4148), 1000 V (1N4007)' },
    ],
  },
  pot: {
    id: 'pot', name: 'Potentiometer', job: 'A resistor track with a sliding contact: a knob that sets a resistance or a voltage.',
    facts: [
      { label: 'Leg 1', text: 'one end of the track' },
      { label: 'Wiper', text: 'the middle leg, the slider the knob moves' },
      { label: 'Leg 3', text: 'the other end of the track' },
      { label: '10 kΩ', text: 'the whole track, end to end' },
    ],
  },
  mosfet: {
    id: 'mosfet', name: 'N-channel MOSFET', job: 'A voltage-controlled switch: a few volts on the gate connect drain to source, with no gate current.',
    facts: [
      { label: 'Gate', text: 'left leg: the control, insulated from the rest' },
      { label: 'Drain', text: 'middle leg (and the tab): the load connects here' },
      { label: 'Source', text: 'right leg: to ground' },
      { label: 'Body diode', text: 'source to drain inside: backwards, it conducts' },
    ],
  },
  regulator: {
    id: 'regulator', name: 'Voltage regulator', job: 'Holds its output at a fixed voltage (5 V for an LM7805) whatever its input does, above about 7 V.',
    facts: [
      { label: 'IN', text: 'left leg: the higher, unsteady supply' },
      { label: 'GND', text: 'middle leg and the tab: ground' },
      { label: 'OUT', text: 'right leg: a steady 5.0 V' },
      { label: 'Heat', text: '(V_in − V_out) × I: big loads need a heatsink' },
    ],
  },
  chip: {
    id: 'chip', name: '14-pin logic chip', job: 'Four (or six) logic gates in one package, powered from pin 14 and pin 7.',
    facts: [
      { label: 'Notch', text: 'marks the pin 1 end' },
      { label: 'Pin 1', text: 'next to the notch; count anticlockwise from it' },
      { label: 'Pin 14', text: 'VCC: + (2–6 V for 74HC)' },
      { label: 'Pin 7', text: 'GND' },
    ],
  },
  toggle: {
    id: 'toggle', name: 'Slide switch', job: 'Stays where you put it: on (joined) or off (open), until you move it again.',
    facts: [
      { label: 'Slider', text: 'pushed across: closed, current flows' },
      { label: 'Legs', text: 'the two contacts it joins' },
      { label: 'Pull-down', text: 'a resistor to ground keeps the input at 0 when it’s open' },
    ],
  },
};

export const FORMULAS: Record<string, Formula> = {
  ohm: {
    name: "Ohm's law", expr: 'V = I × R',
    terms: [['V', 'voltage across the part (volts)'], ['I', 'current through it (amps)'], ['R', 'its resistance (ohms)']],
    when: 'Any resistor: know two, work out the third (I = V ÷ R, R = V ÷ I).',
  },
  led: {
    name: 'LED resistor', expr: 'R = (V_supply − V_LED) ÷ I',
    terms: [['V_supply', 'the supply voltage'], ['V_LED', 'the LED’s drop, about 2 V for red'], ['I', 'the current you want, e.g. 15 mA']],
    when: 'The resistor takes whatever voltage the LED doesn’t.',
  },
  kvl: {
    name: 'Voltages round a loop', expr: 'V_supply = V₁ + V₂ + …',
    terms: [['V₁, V₂', 'the voltage each part takes']],
    when: 'Going once round any loop, the drops add up to what the supply gives (Kirchhoff’s voltage law).',
  },
  series: {
    name: 'Series and parallel', expr: 'series: I same, V adds · parallel: V same, I adds',
    terms: [['series', 'one path: the same current through every part'], ['parallel', 'side by side: each branch gets the full voltage, currents add']],
    when: 'Two LEDs in series share one current; in parallel the supply feeds both.',
  },
  divider: {
    name: 'Voltage divider', expr: 'V_out = V_in × R₂ ÷ (R₁ + R₂)',
    terms: [['R₁', 'top resistor (to the supply)'], ['R₂', 'bottom resistor (to ground)'], ['I', 'V_in ÷ (R₁ + R₂) flows through both']],
    when: 'The ratio sets the voltage; the size sets the current.',
  },
  kcl: {
    name: 'Currents at a junction', expr: 'I_in = I_1 + I_2 + …',
    terms: [['I_in', 'the current arriving at a point'], ['I_1, I_2', 'the currents leaving it by each branch']],
    when: 'Whatever flows into a point flows out again (Kirchhoff’s current law): parallel branch currents add up at the supply.',
  },
  bridge: {
    name: 'Balanced bridge', expr: 'R2 ÷ R1 = R4 ÷ R3',
    terms: [['R1, R2', 'the left divider (top, bottom)'], ['R3, R4', 'the right divider (top, bottom)']],
    when: 'When the ratios match, both taps sit at the same voltage and the meter between them reads zero.',
  },
  npn: {
    name: 'Transistor switch', expr: 'I_B = (V − 0.7) ÷ R_B · I_C ≤ β × I_B',
    terms: [['I_B', 'base current, set by the base resistor R_B'], ['0.7 V', 'the base-emitter drop'], ['β', 'the gain, about 200 for a BC547'], ['I_C', 'collector current: what the load needs']],
    when: 'Fully on (saturated) when β × I_B is comfortably more than the load needs; then the load sets I_C, not the transistor.',
  },
  binary: {
    name: 'Binary place values', expr: '1101 = 8 + 4 + 0 + 1 = 13',
    terms: [['bit', 'one digit, 0 or 1: one switch, one LED'], ['place values', '…, 8, 4, 2, 1: each twice the one to its right'], ['4 bits', 'count 0 to 15; 8 bits (a byte) count 0 to 255']],
    when: 'Add the place values of the bits that are 1.',
  },
  logic: {
    name: 'AND and OR', expr: 'AND: series · OR: parallel',
    terms: [['A AND B', '1 only when both are 1'], ['A OR B', '1 when either (or both) is 1'], ['truth table', 'the output for every combination of inputs']],
    when: 'Switches in series need all of them closed; side by side, any one will do.',
  },
  inverter: {
    name: 'Inverter (NOT)', expr: 'out = NOT A · I_LED = (V − V_LED) ÷ R_pull-up',
    terms: [['pull-up', 'resistor from + to the output: holds it high'], ['transistor', 'pulls the output low when its input is on']],
    when: 'Output high unless the transistor pulls it down; size the pull-up for the load’s current.',
  },
  nand: {
    name: 'NAND', expr: 'out = NOT (A AND B)',
    terms: [['series pull-down', 'two transistors: both must be on to pull the output low'], ['universal', 'NOT, AND, OR, anything, can be built from NANDs']],
    when: 'The opposite of AND: low only when every input is high.',
  },
  xor: {
    name: 'XOR (exclusive OR)', expr: 'out = A XOR B = 1 when A ≠ B',
    terms: [['changeover', 'a switch with a common leg that joins one of two others'], ['travellers', 'the two wires between the switches']],
    when: 'Either input flips the output; it is the sum bit when adding two bits.',
  },
  chip: {
    name: '14-pin logic chip', expr: 'VCC = pin 14 · GND = pin 7',
    terms: [['notch', 'marks the pin 1 end; pins count anticlockwise from it'], ['quad 2-input', 'four gates: 1,2→3 · 4,5→6 · 9,10→8 · 12,13→11'], ['pull-down', '10 kΩ to GND holds an input low when nothing drives it']],
    when: 'Power first, then wire gates by their pin numbers; never leave a CMOS input floating.',
  },
  adder: {
    name: 'Half adder', expr: 'sum = A XOR B · carry = A AND B',
    terms: [['sum', 'the right-hand digit of A + B'], ['carry', 'the 1 carried to the next column (1 + 1 = 10)']],
    when: 'Two bits in, two out; a full adder adds a carry in as well.',
  },
  latch: {
    name: 'SR latch', expr: 'Q = NAND(S̄, Q̄) · Q̄ = NAND(R̄, Q)',
    terms: [['S̄ (set)', 'pulled low by START: Q goes to 1'], ['R̄ (reset)', 'pulled low by STOP: Q goes to 0'], ['both high', 'hold: Q stays what it was']],
    when: 'Feedback makes memory: each output holds the other gate’s input.',
  },
  'series-leds': {
    name: 'LEDs in series', expr: 'R = (V − n × V_f) ÷ I',
    terms: [['n', 'how many LEDs in the string'], ['V_f', 'each LED’s forward voltage'], ['I', 'the one current through all of them']],
    when: 'One current through the whole string; the forward voltages add up.',
  },
  colours: {
    name: 'Forward voltage by colour', expr: 'red 2.0 · yellow 2.1 · green 2.2 · blue/white 3.0 V',
    terms: [['V_f', 'the voltage a lit LED keeps for itself'], ['bluer', 'more energy per electron, so more volts']],
    when: 'Size each colour’s resistor from its own V_f.',
  },
  combine: {
    name: 'Combining resistors', expr: 'series: R₁ + R₂ · parallel: R₁ × R₂ ÷ (R₁ + R₂)',
    terms: [['series', 'always more than the biggest'], ['parallel', 'always less than the smallest'], ['equal pair', 'in parallel: exactly half']],
    when: 'Make a value you don’t have, or share heat between two resistors.',
  },
  short: {
    name: 'Short circuit', expr: 'V_shorted ≈ 0 · I = V ÷ R_rest',
    terms: [['short', 'a near-zero resistance path across a part'], ['R_rest', 'whatever is left in the loop to limit the current']],
    when: '0 V across a part that should be working means its legs are joined.',
  },
  loop: {
    name: 'Closed and open loops', expr: 'open loop: I = 0 · V_gap = V_supply',
    terms: [['closed', 'a complete path from + back to −'], ['open', 'a gap anywhere: no current anywhere in the loop']],
    when: 'Walk the meter along the return path: the reading jumps at the gap.',
  },
  power: {
    name: 'Power', expr: 'P = V × I = I² × R',
    terms: [['P', 'watts: energy per second'], ['I_total', 'the sum of every branch current'], ['mA·h ÷ mA', 'battery life in hours']],
    when: 'Add up every branch and check the supply’s rating.',
  },
  diode: {
    name: 'Diode in series', expr: 'I = (V − 0.7 − V_LED) ÷ R',
    terms: [['0.7 V', 'a silicon diode’s forward drop'], ['reverse', 'blocked: no current at all']],
    when: 'A series diode costs 0.7 V and blocks a reversed supply.',
  },
  rheostat: {
    name: 'Potentiometer as a resistor', expr: 'R = R_track × position',
    terms: [['position', '0 at leg 1, 1 at leg 3'], ['safety resistor', 'in series, for when the knob reaches 0 Ω']],
    when: 'One end and the wiper: a resistance the knob sets.',
  },
  pot: {
    name: 'Potentiometer as a divider', expr: 'V_wiper = V × (1 − position)',
    terms: [['leg 1', 'on +'], ['leg 3', 'on ground'], ['position', 'counted from leg 1']],
    when: 'All three legs: an adjustable voltage, from 0 V to the supply.',
  },
  sensor: {
    name: 'Sensor divider', expr: 'V = V_supply × R_s ÷ (R_f + R_s)',
    terms: [['R_s', 'the sensor’s resistance now'], ['R_f', 'the fixed partner: equal to R_s in mid-range']],
    when: 'A resistance that changes becomes a voltage a chip can read.',
  },
  loaded: {
    name: 'Divider with a load', expr: 'V = V_in × (R₂ ∥ R_L) ÷ (R₁ + R₂ ∥ R_L)',
    terms: [['R_L', 'the load, in parallel with the bottom resistor'], ['stiff', 'R₂ much smaller than R_L: the load hardly matters']],
    when: 'Anything on the output pulls it down; design for it.',
  },
  caps: {
    name: 'Combining capacitors', expr: 'parallel: C₁ + C₂ · series: C₁ × C₂ ÷ (C₁ + C₂)',
    terms: [['parallel', 'capacitance adds (more charge at the same voltage)'], ['series', 'less capacitance, more voltage rating']],
    when: 'The opposite of resistors. τ = R × C scales with the total.',
  },
  regulator: {
    name: 'Linear regulator', expr: 'V_out = 5 V · P = (V_in − V_out) × I',
    terms: [['dropout', 'V_in must be about 2 V above V_out'], ['P', 'the heat the regulator burns']],
    when: 'Design everything after it for 5 V.',
  },
  gain: {
    name: 'Saturating a transistor', expr: 'I_B ≥ I_load ÷ β, × 5 to 10 for margin',
    terms: [['β', 'about 200 for a BC547'], ['R_B', '(V − 0.7) ÷ I_B'], ['saturated', 'fully on: the load sets the current']],
    when: 'Enough base current that the transistor isn’t the limit.',
  },
  mosfet: {
    name: 'MOSFET switch', expr: 'on when V_GS > V_th · I_gate = 0',
    terms: [['V_th', 'about 2 V for a logic-level IRLZ44N'], ['R_on', 'about 0.03 Ω when fully on'], ['pull-down', '10 kΩ gate to source']],
    when: 'Voltage switches it; a pull-down switches it off reliably.',
  },
  'diode-or': {
    name: 'Diode OR', expr: 'OUT = A OR B (minus 0.7 V)',
    terms: [['diodes', 'one from each input, pointing into the output'], ['isolation', 'no input can feed another']],
    when: 'Combine signals or supplies so they can’t back-feed each other.',
  },
  universal: {
    name: 'NAND is universal', expr: 'NOT A = NAND(A, A) · A AND B = NOT NAND(A, B)',
    terms: [['tied inputs', 'a NAND becomes an inverter'], ['universal', 'any logic can be built from NANDs']],
    when: 'Make the gate you need from the chip you have.',
  },
  demorgan: {
    name: 'De Morgan’s laws', expr: 'NOT(A·B) = Ā + B̄ · NOT(A+B) = Ā·B̄',
    terms: [['bar', 'inverted'], ['swap', 'invert everything and AND ↔ OR']],
    when: 'OR from NANDs: NAND(Ā, B̄) = A + B.',
  },
  xnor: {
    name: 'XNOR and XOR tricks', expr: 'A XNOR B = NOT(A ⊕ B) · x ⊕ 1 = NOT x',
    terms: [['XNOR', '1 when the inputs match'], ['x ⊕ 0', 'passes x through']],
    when: 'Equality tests, and switchable inverters.',
  },
  parity: {
    name: 'Parity', expr: 'P = A ⊕ B ⊕ C ⊕ …',
    terms: [['odd parity', '1 when an odd number of bits are 1'], ['parity bit', 'added so the total of 1s comes out even']],
    when: 'One flipped bit changes the parity: the receiver notices.',
  },
  words: {
    name: 'Words to logic', expr: '“and” → · · “or” → + · “not” → bar',
    terms: [['brackets', 'follow the sentence: the bracket is the first gate'], ['8 rows', 'a 3-input truth table to check against']],
    when: 'Write the expression from the spec, then check every row.',
  },
  sop: {
    name: 'Sum of products', expr: 'OUT = (AND of each true row) + …',
    terms: [['product', 'an AND of inputs, inverted where they’re 0'], ['sum', 'all those ANDs ORed together']],
    when: 'Any truth table becomes gates; then simplify (majority = AB + BC + AC).',
  },
  mux: {
    name: 'Multiplexer', expr: 'OUT = A·S̄ + B·S',
    terms: [['S', 'the select line'], ['NAND form', 'NAND(NAND(A, S̄), NAND(B, S))']],
    when: 'Choose which input reaches the output.',
  },
  decoder: {
    name: 'Decoder', expr: 'Y0 = Ā·B̄ · Y1 = A·B̄ · Y2 = Ā·B · Y3 = A·B',
    terms: [['one-hot', 'exactly one output is 1'], ['n inputs', '2ⁿ outputs']],
    when: 'Turn a binary address into a single select line.',
  },
  comparator: {
    name: 'Code comparator', expr: 'OPEN = D3 · D̄2 · D1 · D̄0',
    terms: [['inverted bits', 'the ones that must be 0'], ['AND tree', 'n conditions need n − 1 two-input ANDs']],
    when: 'Matches exactly one of 2ⁿ codes.',
  },
  driver: {
    name: 'Driving a load from logic', expr: 'I_B = (5 − 0.7) ÷ R_B · I_pin ≤ 20 mA',
    terms: [['logic pin', 'a signal: about 20 mA at most'], ['transistor', 'carries the load from the supply']],
    when: 'Anything over a few mA gets a transistor (or MOSFET) driver.',
  },
  'full-adder': {
    name: 'Full adder', expr: 'SUM = A ⊕ B ⊕ Cin · COUT = A·B + Cin·(A ⊕ B)',
    terms: [['Cin', 'the carry from the column to the right'], ['COUT', '1 when two or more inputs are 1']],
    when: 'Chain one per bit: COUT into the next Cin.',
  },
  'd-latch': {
    name: 'D latch', expr: 'E = 1: Q = D · E = 0: Q holds',
    terms: [['E', 'enable (STORE)'], ['S̄, R̄', 'NAND(D, E) and NAND(D̄, E) into an SR latch']],
    when: 'Stores one bit; eight make a byte register.',
  },
  fsm: {
    name: 'State decoding', expr: 'RED = S̄1 · AMBER = S0 · GREEN = S1·S̄0',
    terms: [['state', 'a number held in bits'], ['output column', 'one function of the state bits per output']],
    when: 'Read each output’s column of the state table as logic.',
  },
  rc: {
    name: 'RC time constant', expr: 'τ = R × C',
    terms: [['τ', 'the time to reach 63 % of the final voltage (seconds)'], ['R', 'ohms'], ['C', 'farads (100 µF = 0.0001 F)'], ['V(t)', 'V × (1 − e^(−t/τ))']],
    when: 'After 1 τ the capacitor is 63 % full, after 5 τ it’s all but full.',
  },
};

const LEVEL: Record<string, { parts: PartId[]; formulas: string[]; generators: string[] }> = {
  'w0-01-first-light': { parts: ['led', 'resistor', 'breadboard'], formulas: ['ohm', 'led'], generators: ['led-resistor', 'ohm'] },
  'w0-02-wrong-way-round': { parts: ['led', 'multimeter'], formulas: ['kvl', 'led'], generators: ['led-resistor', 'series-voltage'] },
  'w0-03-side-by-side': { parts: ['led', 'resistor'], formulas: ['series', 'led'], generators: ['series-voltage', 'parallel-total'] },
  'w0-04-split-the-difference': { parts: ['resistor', 'multimeter'], formulas: ['divider', 'ohm'], generators: ['divider'] },
  'w0-05-slow-blink': { parts: ['capacitor', 'button'], formulas: ['rc'], generators: ['rc-charge'] },
  'w0-06-fork-in-the-road': { parts: ['resistor', 'led'], formulas: ['kcl', 'ohm'], generators: ['parallel-total', 'series-parallel'] },
  'w0-07-push-to-light': { parts: ['button', 'breadboard'], formulas: ['ohm', 'led'], generators: ['led-resistor'] },
  'w0-08-stack-them-up': { parts: ['battery', 'multimeter'], formulas: ['kvl', 'led'], generators: ['series-voltage'] },
  'w0-09-balance-the-bridge': { parts: ['resistor', 'multimeter'], formulas: ['bridge', 'divider'], generators: ['bridge', 'divider'] },
  'w0-10-switch-it': { parts: ['transistor', 'resistor'], formulas: ['npn', 'ohm', 'led'], generators: ['ohm', 'led-resistor'] },
  'w1-01-count-in-lights': { parts: ['led', 'multimeter'], formulas: ['binary', 'led'], generators: ['led-resistor'] },
  'w1-02-both': { parts: ['button', 'led'], formulas: ['logic', 'series'], generators: ['led-resistor'] },
  'w1-03-either': { parts: ['button', 'led'], formulas: ['logic', 'series'], generators: ['led-resistor', 'parallel-total'] },
  'w1-04-not': { parts: ['transistor', 'resistor'], formulas: ['inverter', 'npn', 'led'], generators: ['led-resistor', 'ohm'] },
  'w1-05-not-both': { parts: ['transistor'], formulas: ['nand', 'inverter', 'npn'], generators: ['led-resistor'] },
  'w1-06-stairwell': { parts: ['led'], formulas: ['xor', 'logic'], generators: ['led-resistor'] },
  'w1-07-power-the-chip': { parts: ['multimeter'], formulas: ['chip', 'nand'], generators: ['led-resistor'] },
  'w1-08-half-adder': { parts: ['led'], formulas: ['adder', 'xor', 'chip'], generators: ['led-resistor'] },
  'w1-09-remember': { parts: ['button'], formulas: ['latch', 'nand', 'chip'], generators: ['led-resistor'] },
  'w0-11-two-in-a-row': { parts: ['led', 'resistor'], formulas: ['series-leds', 'kvl'], generators: ['series-leds', 'led-resistor'] },
  'w0-12-mixed-colours': { parts: ['led'], formulas: ['colours', 'led'], generators: ['led-resistor', 'parallel-total'] },
  'w0-13-make-do': { parts: ['resistor'], formulas: ['combine', 'led'], generators: ['combine-resistors', 'parallel-total'] },
  'w0-14-bypassed': { parts: ['multimeter', 'led'], formulas: ['short', 'ohm'], generators: ['ohm', 'series-voltage'] },
  'w0-15-dead-rail': { parts: ['breadboard', 'multimeter'], formulas: ['loop', 'kvl'], generators: ['series-voltage'] },
  'w0-16-power-budget': { parts: ['led', 'resistor'], formulas: ['power', 'kcl'], generators: ['parallel-total', 'led-resistor'] },
  'w0-17-one-way': { parts: ['diode', 'led'], formulas: ['diode', 'led'], generators: ['diode-drop'] },
  'w0-18-turn-it-down': { parts: ['pot', 'led'], formulas: ['rheostat', 'led'], generators: ['rheostat'] },
  'w0-19-set-the-level': { parts: ['pot', 'multimeter'], formulas: ['pot', 'divider'], generators: ['pot-wiper', 'divider'] },
  'w0-20-wrong-sensor': { parts: ['resistor', 'multimeter'], formulas: ['sensor', 'divider'], generators: ['divider'] },
  'w0-21-under-load': { parts: ['resistor'], formulas: ['loaded', 'divider', 'combine'], generators: ['loaded-divider', 'divider'] },
  'w0-22-double-up': { parts: ['capacitor', 'button'], formulas: ['caps', 'rc'], generators: ['parallel-caps', 'rc-charge'] },
  'w0-23-regulated': { parts: ['regulator', 'led'], formulas: ['regulator', 'led'], generators: ['regulator-led'] },
  'w0-24-enough-gain': { parts: ['transistor', 'resistor'], formulas: ['gain', 'npn'], generators: ['transistor-base', 'led-resistor'] },
  'w0-25-heavy-lifting': { parts: ['mosfet', 'led'], formulas: ['mosfet', 'led'], generators: ['led-resistor'] },
  'w1-10-diode-or': { parts: ['diode', 'toggle'], formulas: ['diode-or', 'diode', 'logic'], generators: ['diode-drop'] },
  'w1-11-chip-inverter': { parts: ['chip', 'toggle'], formulas: ['chip', 'inverter'], generators: ['gate-led'] },
  'w1-12-and-from-nand': { parts: ['chip'], formulas: ['universal', 'nand'], generators: ['gate-led'] },
  'w1-13-or-from-nand': { parts: ['chip'], formulas: ['demorgan', 'universal'], generators: ['gate-led'] },
  'w1-14-same-or-different': { parts: ['chip', 'toggle'], formulas: ['xnor', 'xor'], generators: ['gate-led'] },
  'w1-15-odd-one-out': { parts: ['chip', 'toggle'], formulas: ['parity', 'xor'], generators: ['gate-led'] },
  'w1-16-burglar-alarm': { parts: ['chip', 'toggle'], formulas: ['words', 'logic'], generators: ['gate-led'] },
  'w1-17-majority-vote': { parts: ['chip'], formulas: ['sop', 'logic'], generators: ['gate-led'] },
  'w1-18-pick-one': { parts: ['chip', 'toggle'], formulas: ['mux', 'demorgan'], generators: ['gate-led'] },
  'w1-19-one-of-four': { parts: ['chip'], formulas: ['decoder', 'binary'], generators: ['gate-led'] },
  'w1-20-crack-the-code': { parts: ['chip', 'toggle'], formulas: ['comparator', 'binary'], generators: ['gate-led'] },
  'w1-21-drive-it-harder': { parts: ['chip', 'transistor'], formulas: ['driver', 'gain'], generators: ['transistor-base', 'gate-led'] },
  'w1-22-full-adder': { parts: ['chip'], formulas: ['full-adder', 'adder'], generators: ['gate-led'] },
  'w1-23-hold-that-bit': { parts: ['chip', 'button'], formulas: ['d-latch', 'latch'], generators: ['gate-led'] },
  'w1-24-traffic-lights': { parts: ['chip', 'toggle'], formulas: ['fsm', 'binary'], generators: ['gate-led'] },
};

/** A stable seed per level so the worked example is the same each time you open it. */
const seedOf = (id: string) => [...id].reduce((h, c) => (h * 31 + c.charCodeAt(0)) >>> 0, 7);

export function spreads(level: LevelDef, section: Section): Spread[] {
  const plan = LEVEL[level.id] ?? { parts: [], formulas: ['ohm'], generators: ['ohm'] };
  if (section === 'theory') {
    const cls = classForLevel(level.id);
    return [
      ...plan.parts.map((p) => ({ kind: 'part' as const, part: PARTS[p] })),
      ...(cls ? cls.steps.map((step, index) => ({ kind: 'step' as const, cls, step, index })) : []),
      ...(cls ? [{ kind: 'check' as const, cls }] : []),
    ];
  }
  if (section === 'math') {
    const gens = plan.generators.filter((g) => GENERATORS.some((x) => x.id === g));
    return [
      { kind: 'formulas', formulas: plan.formulas.map((f) => FORMULAS[f]!).filter(Boolean) },
      ...gens.map((g) => ({ kind: 'worked' as const, generator: g, seed: seedOf(level.id + g) })),
      { kind: 'practice', generator: gens[0] ?? 'ohm' },
    ];
  }
  return [];
}
